// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	netmonMapCounters       = "counters"
	netmonMapEvents         = "events"
	netmonProgCgroupEgress  = "cgroup_egress"
	netmonProgCgroupIngress = "cgroup_ingress"
	netmonProgConnect4      = "connect4"
	netmonProgConnect6      = "connect6"
	netmonProgSendmsg4      = "sendmsg4"
	netmonProgSendmsg6      = "sendmsg6"
)

// loadNetmon returns the embedded CollectionSpec for netmon.
func loadNetmon() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NetmonBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load netmon: %w", err)
	}

	return spec, err
}

// loadNetmonObjects loads netmon and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*netmonObjects
//	*netmonPrograms
//	*netmonMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadNetmonObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadNetmon()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// netmonSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netmonSpecs struct {
	netmonProgramSpecs
	netmonMapSpecs
	netmonVariableSpecs
}

// netmonProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netmonProgramSpecs struct {
	CgroupEgress  *ebpf.ProgramSpec `ebpf:"cgroup_egress"`
	CgroupIngress *ebpf.ProgramSpec `ebpf:"cgroup_ingress"`
	Connect4      *ebpf.ProgramSpec `ebpf:"connect4"`
	Connect6      *ebpf.ProgramSpec `ebpf:"connect6"`
	Sendmsg4      *ebpf.ProgramSpec `ebpf:"sendmsg4"`
	Sendmsg6      *ebpf.ProgramSpec `ebpf:"sendmsg6"`
}

// netmonMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netmonMapSpecs struct {
	Counters *ebpf.MapSpec `ebpf:"counters"`
	Events   *ebpf.MapSpec `ebpf:"events"`
}

// netmonVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netmonVariableSpecs struct {
}

// netmonObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadNetmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type netmonObjects struct {
	netmonPrograms
	netmonMaps
	netmonVariables
}

func (o *netmonObjects) Close() error {
	return _NetmonClose(
		&o.netmonPrograms,
		&o.netmonMaps,
	)
}

// netmonMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadNetmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type netmonMaps struct {
	Counters *ebpf.Map `ebpf:"counters"`
	Events   *ebpf.Map `ebpf:"events"`
}

func (m *netmonMaps) Close() error {
	return _NetmonClose(
		m.Counters,
		m.Events,
	)
}

// netmonVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadNetmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type netmonVariables struct {
}

// netmonPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadNetmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type netmonPrograms struct {
	CgroupEgress  *ebpf.Program `ebpf:"cgroup_egress"`
	CgroupIngress *ebpf.Program `ebpf:"cgroup_ingress"`
	Connect4      *ebpf.Program `ebpf:"connect4"`
	Connect6      *ebpf.Program `ebpf:"connect6"`
	Sendmsg4      *ebpf.Program `ebpf:"sendmsg4"`
	Sendmsg6      *ebpf.Program `ebpf:"sendmsg6"`
}

func (p *netmonPrograms) Close() error {
	return _NetmonClose(
		p.CgroupEgress,
		p.CgroupIngress,
		p.Connect4,
		p.Connect6,
		p.Sendmsg4,
		p.Sendmsg6,
	)
}

func _NetmonClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed netmon_bpfel.o
var _NetmonBytes []byte
